sudo: required
services:
  - docker
language: node_js
node_js:
  - 8.9.0
before_install:
  - npm install -g gulp
script:
  - gulp build --prod
  - gulp dist
after_success:
  # Build the snap.
  - docker run -v $(pwd):/cwd snapcore/snapcraft sh -c 'cd /cwd && snapcraft'
deploy:
  provider: releases
  api_key:
    secure: D3HtvuI2WsuIFGGji0U7Bh5N++HEG3ZI6HiFdElFyxTokDg90pDhJZ++Sd83V5HzF1xOIimxhVGAOsRBminunn5qGZDuRn87YNEaheAfCan+2h/PvNv09Vl8EsfKbfdFM9wjZCHuYleuzOC0KojelKZeQ9J0eXyTqMq0tfVsPq973OhmF1N+rjqHUfK13+gSnWgmdjIknXJGqFggC3XC9LxDJ8t4jGjgPDBxtPX0hPeWoA3XnEku+tf+cyio47Ueh68lnXG6RWYbGNFQT255EnGly51WemNae75fZyCE/37lGwvjoqwnoTzeGq9udsZSiJSeSCJvo/emmelmUJKvESNGng268R5ZkD4i/RAXchbD6c06z4heJJ+WFLLeQUK8Pmk6fZwX0KwkUAgPBtz1HTx9dt8J5QQPX/7OpSewImKijamzakby+RrSz98liPS+WhHgV2kDrs89FUo0pDdYdOXM7ycCxpoxS4CfCuBq9LRvXcmoyUbrYLe54yNPjqVaXPMvjOHE/Hp74AsYwxUUMmImk7RahlUIM5O2BPrCYqMRz5UlnNk+ihRSewUUz4l9T5S7XxCAaoMYSkRzPmvWH7CZnpwVqufPveStLz2rbZK0AmxRpKIhmm17TOqLzD+oLTT470ekXN3xrOhksb1k8lV0TNRDlFB3zqPv14EhC+g=
  file:
    - dist/pre-built.zip
    - dist/pre-built.tar.gz
  on:
    skip_cleanup: true
    tags: true
